### PR TITLE
Improve editor support

### PR DESCRIPTION
**Pull request by charJe**

### CODE REVIEW

**Comment by charJe** [comment]
Let me know if this works for you.

**Comment by tdrhq** [comment]
@charJe Will try soon. I got a finger injury so I might be out of coding for at least a few days if not more :'(

**Comment by tdrhq** [comment]
@charJe I've been using this for the last few days (I sliced my finger tendon, so it took a long while to recover), and it's working pretty nicely! Not perfect, it fails on large pieces of code, so there are probably edge cases that I haven't drilled down on. But it's working great enough that I can't imagine my life without it now.

**Comment by charJe** [comment]
I actually already made a [better version](https://github.com/charJe/markup/tree/semantic-matching), but it currently doesn't work because it relies on a feature of polymode (nesting) that isn't working properly yet.

**Pull request merged**
