### PR TITLE
Add editor support for Emacs

### PR DESCRIPTION
**Pull request by charJe**

### CODE REVIEW

**Comment by tdrhq** [comment]
Love this! I'm so excited to try it!

**Comment by tdrhq** [comment]
@charJe I think this is progress, but I've been having trouble getting it to work correctly on all cases. Let's talk specifically about indentation for example. The following indents perfectly *without* poly-lisp-html-mode (regular lisp-mode):
```
(markup:deftag s-option (&key value current-selected-value)
  (cond
    ((equal value current-selected-value)
      <option selected="true">,(progn value)</option>)
    (t
      <option>,(progn value)</option>)))
```

with poly-lisp-html-mode, the indentation goes haywire. If I re-indent in line in order, everything works until the last line. Then when I go back to the previous lines and re-indent it starts doing more weird things. In the end it indents like this:

```
(markup:deftag s-option (&key value current-selected-value)
  (cond
    ((equal value current-selected-value)
<option selected="true">,(progn value)</option>)
                                (t
                                 <option>,(progn value)</option>)))
```

I've been trying to debug this for the last couple of days, and so far I've come to the point of finding that `(lisp-ppss)` starts giving the wrong result at the end of the second line (the first element being 0, saying that it's not in parenthesis.. I think).

**Comment by charJe** [comment]
What makes this more interesting is to split up the option tag like so: 
```lisp 
;; lisp indentation
(markup:deftag s-option (&key value current-selected-value)
  (cond
    ((equal value current-selected-value)
     <option selected="true">
     ,(progn value) ;this line should be indented to the right.
     </option>)
    (t
     <option>,(progn value)</option>)))

;; poly-lisp-html indentation
(markup:deftag s-option (&key value current-selected-value)
  (cond
    ((equal value current-selected-value)
<option selected="true"> ;a mess
       ,(progn value)
     </option>)
(t ;a big mess
<option>,(progn value)</option>)))
```
You're right the indentation is inconsistent. It should be noted that if I select the text and press TAB (indent-region) then poly-lisp-html-mode indents correctly.

I'll continue looking into it.

**Comment by tdrhq** [comment]
@charJe Thanks!

**Comment by tdrhq** [comment]
@charJe also if you send me any PRs on this code, I'll merge it quickly without review (unless you specifically want my opinions on something)

**Pull request merged**
